//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureDemo.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultureDemo.Languages.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Case.
        /// </summary>
        public static string Case_CreateCase_Button {
            get {
                return ResourceManager.GetString("Case_CreateCase_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Case:.
        /// </summary>
        public static string Case_CreateCaseTitle_Header {
            get {
                return ResourceManager.GetString("Case_CreateCaseTitle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Created.
        /// </summary>
        public static string Case_CreatedDateT_Label {
            get {
                return ResourceManager.GetString("Case_CreatedDateT_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Description.
        /// </summary>
        public static string Case_Description_Label {
            get {
                return ResourceManager.GetString("Case_Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter case description.
        /// </summary>
        public static string Case_Description_Placeholder {
            get {
                return ResourceManager.GetString("Case_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case description is required.
        /// </summary>
        public static string Case_Description_Validation {
            get {
                return ResourceManager.GetString("Case_Description_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Details.
        /// </summary>
        public static string Case_Details_Label {
            get {
                return ResourceManager.GetString("Case_Details_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case list.
        /// </summary>
        public static string Case_List_Header {
            get {
                return ResourceManager.GetString("Case_List_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Modified.
        /// </summary>
        public static string Case_ModifiedDateT_Label {
            get {
                return ResourceManager.GetString("Case_ModifiedDateT_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Name.
        /// </summary>
        public static string Case_Name_Label {
            get {
                return ResourceManager.GetString("Case_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter case name.
        /// </summary>
        public static string Case_Name_Placeholder {
            get {
                return ResourceManager.GetString("Case_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case name is required.
        /// </summary>
        public static string Case_Name_Validation {
            get {
                return ResourceManager.GetString("Case_Name_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Status.
        /// </summary>
        public static string Case_Status_Label {
            get {
                return ResourceManager.GetString("Case_Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the case list! Below is a list of ALL cases (Cases are randomized on load).
        /// </summary>
        public static string Case_WelcomeMessage_Header {
            get {
                return ResourceManager.GetString("Case_WelcomeMessage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Common_BackToList_Button {
            get {
                return ResourceManager.GetString("Common_BackToList_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel_Button {
            get {
                return ResourceManager.GetString("Common_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Common_Submit_Button {
            get {
                return ResourceManager.GetString("Common_Submit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about &lt;a href=&quot;https://docs.microsoft.com/aspnet/core&quot;&gt;building Web apps with ASP.NET Core&lt;/a&gt;.
        /// </summary>
        public static string Home_WelcomeMessage_Paragraph {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Home_WelcomeTitle_Header {
            get {
                return ResourceManager.GetString("Home_WelcomeTitle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string Language_SelectLanguage_Label {
            get {
                return ResourceManager.GetString("Language_SelectLanguage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cases.
        /// </summary>
        public static string Layout_Cases_Link {
            get {
                return ResourceManager.GetString("Layout_Cases_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string User_CreatedBy_Label {
            get {
                return ResourceManager.GetString("User_CreatedBy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string User_EnterFirstName_Placeholder {
            get {
                return ResourceManager.GetString("User_EnterFirstName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string User_EnterLastName_Placeholder {
            get {
                return ResourceManager.GetString("User_EnterLastName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string User_FirstName_Label {
            get {
                return ResourceManager.GetString("User_FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string User_FirstName_Validation {
            get {
                return ResourceManager.GetString("User_FirstName_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string User_LastName_Label {
            get {
                return ResourceManager.GetString("User_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string User_LastName_Validation {
            get {
                return ResourceManager.GetString("User_LastName_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string User_ModifiedBy_Label {
            get {
                return ResourceManager.GetString("User_ModifiedBy_Label", resourceCulture);
            }
        }
    }
}
